name: CI CD Pipeline
on:
  push:
    branches:
      - "*"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1.2'

    - name: Install Composer Dependencies
      run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

    - name: Run Unit Tests
      run: php vendor/bin/phpunit tests

  build:
    runs-on: ubuntu-latest
	needs: tests
	steps:
	- name: Checkout repository
      uses: actions/checkout@v4
        
    - name: Linting Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
        verbose: true
          format: json


    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build toko madura app to dockerhub
      env:
        DOCKER_CONTENT_TRUST: 1
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}"
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}/tokomadura:${{secrets.DOCKER_TOKOMADURA_TAGS_APP}}